#!/usr/bin/env bash
# Displays "FizzBuzz" when the number is a multiple of 3 and 5.
# Display "Fizz" if the number is a multiple of 3.
# Display "Buzz" when the number is a multiple of 5.
# otherwise, display the number.

for num in {1..100}
do
  if (( num % 3 == 0 && num %5 == 0 ))
  then
     echo "FizzBuzz"
  elif (( num %3 == 0 ))
  then
     echo "Buzz"
  else
    echo "$num"
  fi
done
