#!/usr/bin/env bash
# script that displays "Best School" and displays hi on 9nt iteratian

index=0

while [ $index -lt 10 ]
do 
  if [ $index -eq 9 ]
  then
     echo "Hi"
  fi 
  echo "Best School"
  (( index++ ))
done
